CREATE SCHEMA IF NOT EXISTS user_management;
SET SCHEMA user_management;

CREATE TABLE IF NOT EXISTS USERS (
    id UUID PRIMARY KEY,
    token VARCHAR(255) NOT NULL,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    number VARCHAR(255),
    citycode VARCHAR(255),
    countrycode VARCHAR(255),
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    last_login_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    active BOOLEAN NOT NULL
);
